name: Compile all tunes
on: [push]

jobs:
  compile:
    name: compile
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install abcm2ps ps2eps texlive-font-utils texlive-latex-base
      - name: Build
        run: make build/main.pdf
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: latest
      - name: Add files to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/main.pdf
          asset_name: main.pdf
          asset_content_type: application/pdf
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-pdf
          path: build/*.pdf
